# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a4c63ad1e71ae7bb986220f8cfde0a11f6924f9b486bb3c32ed5d7e4c056c03a498b462d44d3e578dc73034568c69196bac2fad5e555ae3d262c7b3ec48a90

test:
  secret_key_base: 735739927bdcdb762c631a4b810a66e363ddabcd9fcb6d1cff5df6e017b114bc3a142d18b5cbb15b5a33c4dde23f9252b0214748a48e8c7453805ef76e0506d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
